### PR TITLE
[pkg/checker] Fix retrieval of link speed

### LINKED ISSUE #1737: pkg/checker - LinkSpeed incorrect for extremely fast interfaces
Noticed while looking for ethtool-related code, haven't actually tested.

at https://github.com/u-root/u-root/blob/master/pkg/checker/interfaces.go#L43
```go
		if int(eth.Speed) < minSpeed {
			return fmt.Errorf("link speed %d < %d", eth.Speed, minSpeed)
		}
```
`eth.Speed` is a uint16 and should be used in conjunction with `eth.Speed_hi`; the ethtool package calculates this and its `EthtoolCmd.CmdGet()` returns it. However, that value is thrown away by this package.

----

Also, I noticed (as of ethtool 5.4) that `struct ethtool_cmd` is deprecated and `struct ethtool_link_settings` should be used instead. The ethtool package's `EthtoolCmd` struct corresponds to ethtool_cmd. I created an issue there noting this: https://github.com/safchain/ethtool/issues/33

### PR DESCRIPTION
**Pull request by insomniacslk**
Fixes #1737

Tested locally:
```
$ go build && sudo ./fixmynetboot enx4865ee148371
 -> no remediation found for enx4865ee148371 link speed, skipping.
 -> no remediation found for enx4865ee148371 has link-local, stop on error requested. Exiting.
2020/06/29 01:04:50 no link local addresses for interface enx4865ee148371
```

Signed-off-by: Andrea Barberio <insomniac@slackware.it>

### CODE REVIEW

File: pkg/checker/interfaces.go [hunk 1]
```diff
@@ -23,25 +23,17 @@ func InterfaceExists(ifname string) Checker {
 	}
 }
 
-func ethStats(ifname string) (*ethtool.EthtoolCmd, error) {
```
Comment (insomniacslk) [inline pkg/checker/interfaces.go:26]: I've removed this redundant function (hence the change to `LinkAutoneg` below)

File: pkg/checker/interfaces.go [hunk 2]
```diff
@@ -23,25 +23,17 @@ func InterfaceExists(ifname string) Checker {
...
 	return func() error {
-		eth, err := ethStats(ifname)
+		ec := ethtool.EthtoolCmd{}
+		speed, err := ec.CmdGet(ifname)
 		if err != nil {
 			return err
 		}
-		if int(eth.Speed) < minSpeed {
-			return fmt.Errorf("link speed %d < %d", eth.Speed, minSpeed)
+		if int64(speed) < minSpeed {
```
Comment (insomniacslk) [inline pkg/checker/interfaces.go:35]: it's all `int64` now, and the speed is fetched directly with `CmdGet` instead of reading the lower 16 bits as previously

Comment (rjoleary) [reply pkg/checker/interfaces.go:35]: It looks like `CmdGet` returns a `uint32`. Perhaps it makes more sense to use a `uint32` throughout so this function isn't advertising a larger type than what is supported? Or perhaps even create a new `type SpeedMbitps uint32`.

Comment (insomniacslk) [reply pkg/checker/interfaces.go:35]: good idea, I'll make a type alias

Comment (insomniacslk) [reply pkg/checker/interfaces.go:35]: on a second thought, given that this is used only internally in that function, I'll use `uint32` instead of a type alias. Let me know if you have a strong preference to do differently

Comment (insomniacslk) [reply pkg/checker/interfaces.go]: pushed update, PTAL

**Comment by insomniacslk** [comment]
rebased

**Comment by insomniacslk** [comment]
this needs re-approval
