### PR TITLE
pkg/uroot: Fix adding files from a symlinked dir

### LINKED ISSUE #1499: Header files not copied to /go/pkg/include in initramfs
Hi,

I'm trying to get up and running with u-root but after building an initramfs with `u-root` (without any arguments) and then launching with qemu (with `qemu-system-x86_64 -nographic -kernel ~/Downloads/vmlinuz -initrd /tmp/initramfs.linux_amd64.cpio  -append "earlyprintk=ttyS0,115200,keep console=ttyS0" -m 256`) I get errors such as:

```
2019/12/30 08:30:29 Couldn't compile "init": error building go package in "/src/github.com/u-root/u-root/cmds/core/init": # internal/cpu
/go/src/internal/cpu/cpu_x86.s:8: #include: open /go/pkg/include/textflag.h: no such file or directory
```

Looking at the files within the initramfs, it looks as though the error message is correct.. there are no files within `/go/pkg/include`:

```
cpio -itv < initramfs.linux_amd64.cpio | grep go/pkg/include
drwxr-xr-x   0 root     root            0 Jan  1  1970 go/pkg/include
```

If I manually extract the files from the initramfs, `cp go/src/runtime/*.h go/pkg/include`, then repackage the initramfs, it seems to fix the problem but I'm guessing I shouldn't have to do this. Am I doing something wrong?

I'm using Ubuntu 18.04, will include the output of `go env` below:

```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/sam/.cache/go-build"
GOENV="/home/sam/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/sam/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build287903227=/tmp/go-build -gno-record-gcc-switches"
```

### PR DESCRIPTION
**Pull request by samvrlewis**
This fixes #1499 where I was not able to build a working initramfs using an Ubuntu PPA provided golang version but was able to build a working initramfs using a golang version I built myself. The issue was that the PPA provided golang has a bunch of symlinks that the `addFile` function didn't appear to follow correctly.

```
$ ls /usr/lib/go-1.12/pkg/ -la
total 28
drwxr-xr-x  7 root root 4096 Aug 15 06:32 .
drwxr-xr-x  4 root root 4096 Jan  9 15:49 ..
lrwxrwxrwx  1 root root   34 Aug 15 06:32 include -> ../../../share/go-1.12/pkg/include
```
In the current version of `addFile`, only the `pkg/include` directory is copied across. In this fixed version, the contents are copied across as well. 

I've tested this updated version with both the PPA provided golang and the version I've built myself, and both appear to work fine now.

Feel free to let me know if I've misunderstood anything or if there are any changes I should make.

### CODE REVIEW

File: pkg/uroot/initramfs/files_test.go [hunk 1]
```diff
@@ -110,10 +110,23 @@ func TestFilesAddFile(t *testing.T) {
...
+		t.Error(err)
+	}
+	defer os.RemoveAll(dir3)
+
 	os.Create(filepath.Join(dir, "foo"))
 	os.Create(filepath.Join(dir, "foo2"))
 	os.Symlink(filepath.Join(dir, "foo2"), filepath.Join(dir2, "foo3"))
 
+	fooDir := filepath.Join(dir3, "fooDir")
+	os.Mkdir(fooDir, os.ModePerm)
```
Comment (golangcibot) [inline pkg/uroot/initramfs/files_test.go]: Error return value of `os.Mkdir` is not checked (from `errcheck`)

File: pkg/uroot/initramfs/files_test.go [hunk 2]
```diff
@@ -110,10 +110,23 @@ func TestFilesAddFile(t *testing.T) {
...
+	symlinkToDir3 := filepath.Join(dir3, "fooSymDir/")
+	os.Symlink(fooDir, symlinkToDir3)
```
Comment (golangcibot) [inline pkg/uroot/initramfs/files_test.go]: Error return value of `os.Symlink` is not checked (from `errcheck`)

File: pkg/uroot/initramfs/files_test.go [hunk 3]
```diff
@@ -110,10 +110,23 @@ func TestFilesAddFile(t *testing.T) {
...
+	os.Create(filepath.Join(fooDir, "foo"))
```
Comment (golangcibot) [inline pkg/uroot/initramfs/files_test.go]: Error return value of `os.Create` is not checked (from `errcheck`)

File: pkg/uroot/initramfs/files_test.go [hunk 4]
```diff
@@ -110,10 +110,23 @@ func TestFilesAddFile(t *testing.T) {
...
+	os.Create(filepath.Join(fooDir, "bar"))
```
Comment (golangcibot) [inline pkg/uroot/initramfs/files_test.go]: Error return value of `os.Create` is not checked (from `errcheck`)
