### PR TITLE
Fix ps to be stable with terminated processes

### LINKED ISSUE #28: ps.go broken: bug between walk at /proc  and reading stats of process
Sometimes when process disappears at the middle of operations in walking and reading stats, we got that weird error:

```
2016/03/09 19:53:37 /proc/7020: lstat /proc/7020: no such file or directory
--- FAIL: TestPsExecution (0.01s)
    ps_test.go:18: Loading Table fails on some point; lstat /proc/7020: no such file or directory
FAIL
FAIL    github.com/u-root/u-root/cmds/ps    0.008s
```

The most probable functions whose may be the guilty of this are:
- ProcessTable.[readStats](https://github.com/u-root/u-root/blob/master/cmds/ps/ps_linux.go#L94)
- ProcessTable.[LoadTable](https://github.com/u-root/u-root/blob/master/cmds/ps/ps_linux.go#L220)

### PR DESCRIPTION
**Pull request by rjoleary**
Procfs is very alive. Subdirectories can be added and removed at
anytime. `os.Walk`ing over `/proc` and expecting a file to exist on a
subsequent syscall is a race condition waiting to happen.

The solution is to implement a simpler version of `os.Walk` which simply
walks over a single directory. Additionally, "file does not exist"
errors are ignored.

I tested this issue by killing many processes per second:

	while true; do /bin/true; done

In another terminal, run:

	for i in {1..1000}; do ./ps > /dev/null; done

No longer will you see fatal error messages and SIGSEVs.

Fixes #28

### CODE REVIEW

File: cmds/ps/ps_linux.go [hunk 1]
```diff
@@ -215,34 +202,33 @@ func (p process) getTime() string {
...
-	err := filepath.Walk(proc, func(name string, fi os.FileInfo, err error) error {
+	// Match all files and directories directly inside of /proc.
+	matches, err := filepath.Glob(filepath.Join(proc, "*"))
+	if err != nil {
+		return err
+	}
+
+	for _, m := range matches {
+		// Filter out files and directories which are not numbers.
+		pid, err := strconv.Atoi(filepath.Base(m))
```
Comment (rminnich) [inline cmds/ps/ps_linux.go]: here you turn it to an int and above you turn it to a string. Might be simpler to have a function or use regexp to just match numeric strings.

**Comment by bensallen** [comment]
@rjoleary Can you turn the example local test you referenced into a test in ps_test.go, so we can catch this in the future?

**Comment by rjoleary** [comment]
@bensallen It should be easy enough. The reason it wasn't added before is such a test cannot be 100% deterministic. If it passes, it is not guaranteed to pass again. However, it might still be useful.
