### PR TITLE
gzip: compress stdin to stdout without stat

### LINKED ISSUE #1356: rewrite gzip package to be unix-like
the gzip package has unnecessary dependencies on linux, e.g. it uses /dev/stdin as a filename. Further, it stats stdin to see if it is a pipe, or in a new PR, to see that it's not a character device, and both those actions are wrong. 

when there are no args to gzip, it should use os.Stdin and not stat it at all. It's perfectly legal to read it whatever it may be. And we certainly should not embed linux-isms in code when we don't need it.

### PR DESCRIPTION
**Pull request by binjip978**
Allow compression from stdin with force, `gzip -f` should return
compressed stdin to stdout and not return an error "no input files".
fixes #1356

Signed-off-by: Sergei Semenchuk <binjip978@gmail.com>

### CODE REVIEW

File: cmds/core/gzip/gzip.go [hunk 1]
```diff
@@ -32,15 +32,21 @@ func main() {
...
-	var input []string
-	if opts.Stdin {
-		input = []string{"/dev/stdin"}
+	var input []gzip.File
+	args := cmdLine.Args()
+
+	if len(args) == 0 {
+		// no args given, compress stdin to stdout
+		opts.Stdin = true
+		opts.Stdout = true
```
Comment (hugelgupf) [inline cmds/core/gzip/gzip.go:41]: huh, I figured opts.Stdin and opts.Stdout should already be true here, because validate assigns them to be true if len(cmdLine.Args()) == 0, but I'm a bit confused by the check for ModeCharDevice there, too.

Comment (hugelgupf) [reply cmds/core/gzip/gzip.go:41]: I definitely agree with taking out the path checks, though, I'm just wondering if validate() has a bug

Comment (binjip978) [reply cmds/core/gzip/gzip.go:41]: I agree that setting Stdin and Stdout should be done in one place, so it's better to fix validate. Right now the check works for commands like this `echo "aaaaa" | ./gzip -f`, but it fails for `./gzip -f`, but i think that just checking for empty args in validate should be ok in this case?
```go
	if !moreArgs {
		o.Stdin = true
		// Since there's no filename to derive the output path from, only support
		// outputting to stdout when data is piped from stdin
		o.Stdout = true
	}
```

**Review by rjoleary — APPROVED** [review]
