### PR TITLE
[cmds/core/ping] Implement ping6

### LINKED ISSUE #1009: ping doesn't work for IPv6
From u-root:

```
/# ping -6 2606:4700:4700::1111
1970/01/01 02:58:26 ping failed: Read failed: read ip6 fc00::7efe:90ff:fe41:3f0->2606:4700:4700::1111: i/o timeout
Exception: ping exited with 1
[tty], line 1: ping -6 2606:4700:4700::1111
```

This results in:

```
18:47:20.897252 IP6 fc00::7efe:90ff:fe41:3f0 > one.one.one.one: ICMP6, unknown icmp6 type (8), length 64
	0x0000:  0800 243c 0000 0001 0000 0000 0000 0000
	0x0010:  0000 0000 0000 0000 0000 0000 0000 0000
	0x0020:  0000 0000 0000 0000 0000 0000 0000 0000
	0x0030:  0000 0000 0000 0000 0000 0000 0000 0000
```

From a normal Linux:

```
$ ping6 2606:4700:4700::1111
PING 2606:4700:4700::1111(2606:4700:4700::1111) 56 data bytes
64 bytes from 2606:4700:4700::1111: icmp_seq=1 ttl=60 time=89.3 ms
64 bytes from 2606:4700:4700::1111: icmp_seq=2 ttl=60 time=91.7 ms
```

```
18:47:04.435071 IP6 2002:9242:eb4d::1 > one.one.one.one: ICMP6, echo request, seq 3, length 64
18:47:04.520423 IP6 one.one.one.one > 2002:9242:eb4d::1: ICMP6, echo reply, seq 3, length 64
```

From the output it seems like the ICMP type is reused from IPv4.

Stretch goal: make it possible to ping multicast addresses like `ff02::1`:

```
/# ping -6 ff02::1%ens224
1970/01/01 03:01:37 ping failed: net.Dial(ip6:ipv6-icmp ff02::1%ens224) failed: dial ip6:ipv6-icmp ff02::1%ens224: connect: invalid argument
Exception: ping exited with 1
[tty], line 1: ping -6 ff02::1%ens224
```

### PR DESCRIPTION
**Pull request by insomniacslk**
Fixes #1009

Tested with:

```
$ go build && sudo ./ping -c 3 8.8.8.8
2020/09/15 22:51:10 84 bytes from 8.8.8.8: icmp_seq=1, time=32.758334ms
2020/09/15 22:51:11 84 bytes from 8.8.8.8: icmp_seq=2, time=33.057741ms
2020/09/15 22:51:12 84 bytes from 8.8.8.8: icmp_seq=3, time=32.89407ms
```

```
$ go build && sudo ./ping -6 -c 3 2001:4860:4860::8888
2020/09/15 22:50:52 64 bytes from 2001:4860:4860::8888: icmp_seq=1, time=34.242377ms
2020/09/15 22:50:53 64 bytes from 2001:4860:4860::8888: icmp_seq=2, time=33.450789ms
2020/09/15 22:50:54 64 bytes from 2001:4860:4860::8888: icmp_seq=3, time=37.98115ms
```

Signed-off-by: Andrea Barberio <insomniac@slackware.it>

### CODE REVIEW

**Comment by insomniacslk** [comment]
Uh.. different macros on Plan9? Summoning @rminnich as the plan9 expert

```
2020/09/15 20:57:14 Build environment: GOARCH=amd64 GOOS=plan9 GOROOT=/usr/local/go GOPATH=/go CGO_ENABLED=0
2020/09/15 20:57:14 GOOS is not linux. Did you mean to set GOOS=linux?
2020/09/15 20:57:19 error building: error building go package in "/go/src/github.com/u-root/u-root/bb": # github.com/u-root/u-root/cmds/core/ping/.bb
../cmds/core/ping/.bb/ping.go:112:13: undefined: unix.SetsockoptInt
../cmds/core/ping/.bb/ping.go:112:48: undefined: unix.SOL_IPV6
../cmds/core/ping/.bb/ping.go:112:63: undefined: unix.IPV6_RECVERR
```

**Comment by insomniacslk** [comment]
yeah, it seems that macro is Linux-only :(

File: cmds/core/ping/ping_other.go [hunk 1]
```diff
@@ -0,0 +1,12 @@
+// +build !linux
```
Comment (insomniacslk) [inline cmds/core/ping/ping_other.go:1]: I don't like this, but at least we have ping6 on Linux, and the build for other OSes doesn't fail

File: cmds/core/ping/ping.go [hunk 2]
```diff
@@ -82,18 +87,33 @@ func cksum(bs []byte) uint16 {
 	return ^uint16(sum)
 }
 
-func ping1(netname string, host string, i uint64) (string, error) {
+func ping1(net6 bool, host string, i uint64, waitFor time.Duration) (string, error) {
```
Comment (rminnich) [inline cmds/core/ping/ping.go:90]: Why not just take netname as a parameter?

**Review by rminnich — APPROVED** [review]

File: cmds/core/ping/ping.go (hunk 2 above)
Comment (insomniacslk) [reply cmds/core/ping/ping.go:90]: I use `net6` several times below to tell if it's a ping4 or ping6 request, and the netname is just the string to pass to `Dial` (doing the same with netname wouldn't work)

Comment (insomniacslk) [reply cmds/core/ping/ping.go:90]: (I'll merge this, if you think I should do this differently I'll do that in another PR)
