### PR TITLE
netstat integer overflow

### LINKED ISSUE #3216: `netstat -unix`  complains about `unsigned integer overflow on token 98790705604`
**Describe the bug**

Running `netstat -unix` would error out.

```
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/netstat$ ./netstat -unix
2024/12/01 08:54:21 unsigned integer overflow on token 98790705604
```

**To Reproduce**

HEAD commit, and steps used for reproducing the error,

```
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/netstat$
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/netstat$
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/netstat$ git log -1
commit e3b3cae21292a1c40d75d9066b1aeec446f790ea (HEAD -> main, origin/main, origin/HEAD)
Author: Ronald G Minnich <rminnich@gmail.com>
Date:   Sat Nov 30 19:55:00 2024 -0800

    Fix race in gosh_test.go

    Signed-off-by: Ronald G Minnich <rminnich@gmail.com>
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/netstat$ go build .
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/netstat$ ./netstat -unix
2024/12/01 08:54:21 unsigned integer overflow on token 98790705604
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/netstat$
```

**Expected behavior**

would expect UNIX sockets be printed out.

**Additional context**

### PR DESCRIPTION
**Pull request by jensdrenhaus**
Closes #3216, #3218, #3219

### CODE REVIEW

**Comment by jensdrenhaus** [comment]
Note: The TinyGo regression test fails because the white list of know buildable commands was not adapted in #3276 (revert of TinyGo watchdog support). There is #3278 to fix it

**Review by binjip978 — APPROVED** [review]

File: cmds/core/netstat/netstat_linux.go [hunk 1]
```diff
@@ -261,71 +261,71 @@ func evalProtocols(tcp, udp, udpl, raw, unix, ipv4, ipv6 bool) ([]netstat.Socket
 	if tcp && ipv4 {
 		t, err := netstat.NewSocket(netstat.PROT_TCP)
 		if err != nil {
-			return nil, err
+			return nil, fmt.Errorf("could not create TCP socket: %w", err)
```
Comment (rminnich) [inline cmds/core/netstat/netstat_linux.go:264]: It might be more useful to say:
"evalProtocols creating TCP4 socket: %w"
because the error text will be what want wrong, and your text will be what you were trying to do.
Just this message alone, I would not be sure where to look.

File: cmds/core/netstat/netstat_linux.go [hunk 2]
```diff
@@ -261,71 +261,71 @@ func evalProtocols(tcp, udp, udpl, raw, unix, ipv4, ipv6 bool) ([]netstat.Socket
...
 		}
 		retProtos = append(retProtos, t)
 	}
 
 	if tcp && ipv6 {
 		t, err := netstat.NewSocket(netstat.PROT_TCP6)
 		if err != nil {
-			return nil, err
+			return nil, fmt.Errorf("could not create TCP6 socket: %w", err)
```
Comment (rminnich) [inline cmds/core/netstat/netstat_linux.go:272]: same as above.

File: cmds/core/netstat/netstat_linux.go [hunk 3]
```diff
@@ -261,71 +261,71 @@ func evalProtocols(tcp, udp, udpl, raw, unix, ipv4, ipv6 bool) ([]netstat.Socket
...
 		}
 		retProtos = append(retProtos, t)
 	}
 
 	if udp && ipv4 {
 		t, err := netstat.NewSocket(netstat.PROT_UDP)
 		if err != nil {
-			return nil, err
+			return nil, fmt.Errorf("could not create UDP socket: %w", err)
```
Comment (rminnich) [inline cmds/core/netstat/netstat_linux.go:280]: udp4.

File: cmds/core/netstat/netstat_linux.go [hunk 4]
```diff
@@ -261,71 +261,71 @@ func evalProtocols(tcp, udp, udpl, raw, unix, ipv4, ipv6 bool) ([]netstat.Socket
...
+			return nil, fmt.Errorf("could not create UDP6 socket: %w", err)
 		}
 		retProtos = append(retProtos, t)
 	}
 
 	if udpl && ipv4 {
 		t, err := netstat.NewSocket(netstat.PROT_UDPL)
 		if err != nil {
-			return nil, err
+			return nil, fmt.Errorf("could not create UDPL socket: %w", err)
```
Comment (rminnich) [inline cmds/core/netstat/netstat_linux.go:296]: udpl4, 

same comment as the first one for all these: you're trying to create it, but WHY? it's helpful if you say more about why you were doing it, and let the error tell you what went wrong?

**Comment by jensdrenhaus** [comment]
I somehow managed to accidentally merge the initial commits including the actual fix already (after approval from binjip978). Still want to bring the adaption according to Ron's comments on the error messages in.

**Review by binjip978 — APPROVED** [review]
