### PR TITLE
cmds/core/ip: link set: support any combination of attributes

### LINKED ISSUE #3192: Use `ip link set` to update `mtu` to a new value does not take effect
**Describe the bug**

updating mtu to a new value does not take effect.

**To Reproduce**

See following steps to attempt to update `mtu` to `5000`, but it didn't take effect.

```
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/ip$ ./ip link show testbrg2
6: testbrg2: <BROADCAST,MULTICAST> mtu 1500 state DOWN group default
    link/ether e6:00:18:a8:c0:2f
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/ip$ ./ip link set testbrg2 down type bridge promisc on mtu 5000 arp on
2024/11/19 23:56:52 ip: testbrg2 can't make it down: operation not permitted
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/ip$ sudo ./ip link set testbrg2 down type bridge promisc on mtu 5000 arp on
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/ip$ ./ip link show testbrg2
6: testbrg2: <BROADCAST,MULTICAST> mtu 1500 state DOWN group default
    link/ether e6:00:18:a8:c0:2f
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/ip$ ./ip -d link show testbrg2
6: testbrg2: <BROADCAST,MULTICAST> mtu 1500 state DOWN group default
    link/ether e6:00:18:a8:c0:2f
    bridge hello_time 824633805176 ageing_time 824633805180 vlan_filtering 824633805184 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/ip$
```

**Expected behavior**

`mtu` be updated to `5000`

**Additional context**

### PR DESCRIPTION
**Pull request by RiSKeD**
resolves #3192

### CODE REVIEW

File: cmds/core/ip/link_linux.go [hunk 1]
```diff
@@ -23,7 +23,7 @@ const linkHelp = `Usage: ip link add  [ name ] NAME
 
 	ip link delete { DEVICE | dev DEVICE  } 
 
-	ip link set { DEVICE | dev DEVICE | group DEVGROUP }
```
Comment (binjip978) [inline cmds/core/ip/link_linux.go:26]: I see that we have `setLinkGroup` function but is not used by anyone? Do you plan to remove it or add additional functionality latter?

Comment (RiSKeD) [reply cmds/core/ip/link_linux.go:26]: Yes, you are right. I pushed a commit, which correctly adds the functionality.

**Review by binjip978 — APPROVED** [review]

**Review by leongross — APPROVED** [review]
lgtm
