### PR TITLE
Fix #624: Write test for mkdir and make its permission work correctly

### LINKED ISSUE #624: mkdir command creates a directory with the wrong permission bits
Commit id: f9f8282fe7cd25a719df60214dc4c195896772d6

Steps for reconstruction:
1. From u-root root directory, `cd ./cmds/mkdir && go build .`
2. `umask 22`
3. `./mkdir test`
4. `ls -a -l`
`drw-r--r--  2 userid groupid    4096 Feb 13 11:38 test`

Further Investigation:
The code for mkdir currently has default permission bits to be 0666, which after minus by the umask yield 0644 (as we see above). Shouldn't the default permission code for directory be 0777?

### PR DESCRIPTION
**Pull request by thienhoang23**
* Change its default creation mode to 0777
* Make -m flag work as expected from regular mkdir

Signed-off-by: Thien Hoang <thienhoang@google.com>

### CODE REVIEW

File: cmds/mkdir/mkdir_test.go [hunk 1]
```diff
@@ -0,0 +1,230 @@
...
+}
+
+func TestMkdir(t *testing.T) {
+	// Set Up
+	tmpDir, execPath := testutil.CompileInTempDir(t)
+	defer os.RemoveAll(tmpDir)
+	syscall.Umask(umaskDefault)
+
+	// Error Tests
+	for _, test := range errorTestCases {
```
Comment (rminnich) [inline cmds/mkdir/mkdir_test.go]: If these are really separate tests they ought to be separate functions, so you can see in test output which test series failed.

File: cmds/mkdir/mkdir.go [hunk 2]
```diff
@@ -16,32 +16,93 @@ package main
 import (
 	"flag"
 	"fmt"
+	"log"
 	"os"
+	"strconv"
+	"syscall"
+)
+
+type modeFlag struct {
```
Comment (rminnich) [inline cmds/mkdir/mkdir.go]: I don't understand the need for this struct.

File: cmds/mkdir/mkdir.go [hunk 3]
```diff
@@ -16,32 +16,93 @@ package main
...
+
+const (
+	cmd       = "mkdir [-m mode] [-v] [-p] <directory> [more directories]"
+	StickyBit = 01000
+	SgidBit   = 02000
+	SuidBit   = 04000
 )
 
 var (
+	mode    = &modeFlag{set: false, value: "0777"}
```
Comment (rminnich) [inline cmds/mkdir/mkdir.go]: mode = flag.String("m", "0777", "default mode string")

File: cmds/mkdir/mkdir.go [hunk 4]
```diff
@@ -16,32 +16,93 @@ package main
...
+		flag.Usage()
 		os.Exit(1)
 	}
 	if *mkall {
 		f = os.MkdirAll
 	}
+
+	// Get Correct Access Mode
+	if mode.set {
+		syscall.Umask(0)
```
Comment (rminnich) [inline cmds/mkdir/mkdir.go]: are you sure? Why would you set this to 0? The standard command does not set the umask. What is this for?

File: cmds/mkdir/mkdir.go [hunk 5]
```diff
@@ -16,32 +16,93 @@ package main
...
+	}
+	accMode64bit, err := strconv.ParseUint(mode.value, 8, 32)
```
Comment (rminnich) [inline cmds/mkdir/mkdir.go]: keep the name short, per go convention, m is fine.

File: cmds/mkdir/mkdir.go [hunk 6]
```diff
@@ -16,32 +16,93 @@ package main
...
+	if accMode64bit&SuidBit != 0 {
+		accMode |= os.ModeSetuid
+	}
+
 	for _, name := range flag.Args() {
-		if err := f(name, os.FileMode(*mode)); err != nil {
-			fmt.Printf("%v: %v\n", name, err)
+		if err := f(name, accMode); err != nil {
+			log.Fatalf("%v: %v\n", name, err)
 		} else {
```
Comment (rminnich) [inline cmds/mkdir/mkdir.go]: you don't need the else. log.Fatalf exits.

Comment (rminnich) [reply cmds/mkdir/mkdir.go]: and log.Fatalf is incorrect anyway. The behavior of mkdir is to try to make everything and print errors if things fail. 
so this should be log.Printf()
continue
and remove the else, the continue will make it so you do't need it.

File: cmds/mkdir/mkdir.go [hunk 7]
```diff
@@ -16,32 +16,93 @@ package main
...
 			if *verbose {
 				fmt.Printf("%v\n", name)
 			}
+			// os.Mkdir does not set up SGID and SUID correctly
+			if accMode64bit&SgidBit != 0 || accMode64bit&SuidBit != 0 {
```
Comment (rminnich) [inline cmds/mkdir/mkdir.go]: is  that a bug? this would be worth figuring out

File: cmds/mkdir/mkdir.go [hunk 8]
```diff
@@ -16,32 +16,93 @@ package main
...
+
+	// Get Correct Access Mode
+	if mode.set {
+		syscall.Umask(0)
+	}
+	accMode64bit, err := strconv.ParseUint(mode.value, 8, 32)
+	if err != nil || accMode64bit > 07777 {
+		log.Fatalf("invalid mode '%s'", mode.value)
+	}
+	accMode := os.FileMode(accMode64bit)
```
Comment (rminnich) [inline cmds/mkdir/mkdir.go]: accMode or create mode? This naming is confusing.

File: cmds/mkdir/mkdir.go (hunk 2 above)
Comment (thienhoang23) [reply cmds/mkdir/mkdir.go]: So in mkdir, when you do not set the -m flag, they will use your default creation mode & ~umask to be the creation mode of your directory. However, when you set the -m flag, the umask is effectively set to 0 before the creation mode is taken into consideration. Since flag.String in Go has no way of indicating whether a flag is set or not, because they only return a value, we need to create our own flag for that purpose.

File: cmds/mkdir/mkdir.go (hunk 3 above)
Comment (thienhoang23) [reply cmds/mkdir/mkdir.go]: See above

File: cmds/mkdir/mkdir.go (hunk 2 above)
Comment (rminnich) [reply cmds/mkdir/mkdir.go]: I'll stop by.

Comment (rminnich) [reply cmds/mkdir/mkdir.go]: you can actually test this pretty easily. 
m = flag.String("m", "", "creation mask")

then later:
if *m == "" {
  *m = "0777"
} else {
oldUmask = umask(0)
defer umask(oldUmask)
}

Then further down
mode := strconv.whatever(*m, 8, whatever)

an unset string has value ""

File: cmds/mkdir/mkdir.go (hunk 7 above)
Comment (thienhoang23) [reply cmds/mkdir/mkdir.go]: I have used strace to trace it down to the syscall level, the os.Mkdir calls the mkdirat syscall with the correct permission bits we passed in at that level. However, the SGID and SUID bits were still off. I think that might be a feature of the kernel.

Also, I just noticed that in the original mkdir command, whenever -m flag is used, the command makes a mkdir syscall with the permission bits we passed &~ the umask, following by a fchmod syscall with the actual permission bits we passed in.

So I think the fact that SGID and SUID not set up correctly in os.Mkdir is an expected behavior. Also, I have changed my code to reflect the original design of mkdir

File: cmds/mkdir/mkdir.go (hunk 4 above)
Comment (thienhoang23) [reply cmds/mkdir/mkdir.go]: Fixed. I have changed the design to not mess with Umask anymore but still produce the desire effect. This actually reflects with the original design of mkdir

File: cmds/mkdir/mkdir.go (hunk 2 above)
Comment (thienhoang23) [reply cmds/mkdir/mkdir.go]: Fixed

File: cmds/mkdir/mkdir.go (hunk 5 above)
Comment (thienhoang23) [reply cmds/mkdir/mkdir.go]: Fixed

File: cmds/mkdir/mkdir.go (hunk 6 above)
Comment (thienhoang23) [reply cmds/mkdir/mkdir.go]: Fixed

File: cmds/mkdir/mkdir.go (hunk 8 above)
Comment (thienhoang23) [reply cmds/mkdir/mkdir.go]: Fixed. It's createMode. Sorry for the confusion

File: cmds/mkdir/mkdir_test.go (hunk 1 above)
Comment (thienhoang23) [reply cmds/mkdir/mkdir_test.go]: Fixed

File: cmds/mkdir/mkdir.go [hunk 9]
```diff
@@ -16,32 +16,77 @@ package main
...
+	}
+	if m&SuidBit != 0 {
+		createMode |= os.ModeSetuid
+	}
+
 	for _, name := range flag.Args() {
-		if err := f(name, os.FileMode(*mode)); err != nil {
-			fmt.Printf("%v: %v\n", name, err)
+		if err := f(name, createMode); err != nil {
+			log.Printf("%v: %v\n", name, err)
```
Comment (rminnich) [inline cmds/mkdir/mkdir.go]: we can do this on a future PR, but the Go common way to do this is a log.Printf and a continue, then 
avoid the else.

File: cmds/mkdir/mkdir_test.go [hunk 10]
```diff
@@ -0,0 +1,244 @@
...
+	}
+	for _, file := range files {
+		if file.Name() == filename {
+			return file, nil
+		}
+	}
+	return nil, nil
+}
+
+func removeCreatedFiles(tmpDir string) {
```
Comment (rminnich) [inline cmds/mkdir/mkdir_test.go]: now that you've split the cases is this even necessary any more?

Comment (thienhoang23) [reply cmds/mkdir/mkdir_test.go]: It's still necessary because it is called between test cases, not test suites. So I can restore the state of the tmpDir to default (which is empty) before each test is run

File: cmds/mkdir/mkdir.go (hunk 9 above)
Comment (thienhoang23) [reply cmds/mkdir/mkdir.go]: Fixed
