### PR TITLE
cmds/core/netcat: fix parsing of source-port flag

### LINKED ISSUE #3206: `./netcat -l -p <port>` does not take port number passed in
**Describe the bug**

port number is not taken in.

`./netcat` built from this commit

```
commit b2007a3a212cce4e6b2461bdf58e346e87aeefb2 (HEAD -> main, origin/main, origin/HEAD)
Author: Ronald G Minnich <rminnich@gmail.com>
Date:   Fri Nov 22 14:41:15 2024 -0800

    cmds/dd: remove unused flags from dd func

    Signed-off-by: Ronald G Minnich <rminnich@gmail.com>
```

**To Reproduce**

```
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/netcat$ ./netcat -l -p "31336"
2024/11/24 07:45:11 error: failed to setup listener: listen tcp 0.0.0.0:31337: bind: address already in use
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/netcat$ ./netcat -p 31337 -l
2024/11/24 07:45:26 error: failed to setup listener: listen tcp 0.0.0.0:31337: bind: address already in use
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/netcat$ ./netcat -p 31117 -l
2024/11/24 07:45:33 error: failed to setup listener: listen tcp 0.0.0.0:31337: bind: address already in use
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/netcat$ ./netcat -p 111 -l
2024/11/24 07:45:39 error: failed to setup listener: listen tcp 0.0.0.0:31337: bind: address already in use
xuehaohu@worldpeace:~/go/src/github.com/u-root/u-root/cmds/core/netcat$ sudo ./netcat -p 111 -l
2024/11/24 07:45:48 error: failed to setup listener: listen tcp 0.0.0.0:31337: bind: address already in use
```

**Expected behavior**

port number passed in is taken, and listening on the specified port.

**Additional context**

### PR DESCRIPTION
**Pull request by RiSKeD**
resolves #3206 
The source port flag was not correctly parsed in listen Mode.

Working examples: 
```
➜ ./netcat -l -p 3030 localhost
test
Second shell:
➜ ./netcat -C localhost 3030
2024/11/25 08:54:56 Connection to localhost:3030 [tcp] succeeded
test
```

```
❯ ./netcat -l localhost 7654
test
Second shell:
❯ ./netcat -C localhost 7654
2024/11/25 08:57:05 Connection to localhost:7654 [tcp] succeeded
test
```
Fail with 2 specified ports:
```
❯ ./netcat -l -p 3222 localhost 7654
2024/11/25 08:57:57 error: got more than one port specification
```
The original command supports flags behind arguments, which we do not support(!), because of flag parsing limitations:
```
➜ ./netcat -l localhost -p 7654
2024/11/25 09:01:37 error: invalid port: -p
```

### CODE REVIEW

File: cmds/core/netcat/netcat.go [hunk 1]
```diff
@@ -102,7 +106,7 @@ func evalParams(args []string, f flags) (*netcat.Config, error) {
 
 			port, err := strconv.ParseUint(ports[0], 10, 64)
 			if err != nil {
-				return nil, fmt.Errorf("invalid port: %w", err)
+				return nil, fmt.Errorf("invalid port: %v", ports[0])
```
Comment (rminnich) [inline cmds/core/netcat/netcat.go:109]: you could consider wrapping os.ErrInvalid here so that writing a test is easier at some point.

Comment (RiSKeD) [reply cmds/core/netcat/netcat.go]: I added a commit which wrapps os.ErrInvalid in all the parsing errors.

File: cmds/core/netcat/netcat.go [hunk 2]
```diff
@@ -173,12 +191,12 @@ func evalParams(args []string, f flags) (*netcat.Config, error) {
 			Command: f.execLua,
 		})
 	if err != nil {
-		return nil, err
+		return nil, fmt.Errorf("%w: %v", os.ErrInvalid, err)
```
Comment (leongross) [inline cmds/core/netcat/netcat.go:194]:
```suggestion
		return nil, fmt.Errorf("%w: %w", os.ErrInvalid, err)
```

File: cmds/core/netcat/netcat.go [hunk 3]
```diff
@@ -255,15 +273,15 @@ func evalParams(args []string, f flags) (*netcat.Config, error) {
 
 	config.AccessControl, err = netcat.ParseAccessControl(f.connectionAllowFile, connectionAllowList, f.connectionDenyFile, connectionDenyList)
 	if err != nil {
-		return nil, err
+		return nil, fmt.Errorf("%w: %v", os.ErrInvalid, err)
```
Comment (leongross) [inline cmds/core/netcat/netcat.go:276]: missed that in my prior review, same thing here breaking the CI
```suggestion
		return nil, fmt.Errorf("%w: %w", os.ErrInvalid, err)
```

File: cmds/core/netcat/netcat.go [hunk 4]
```diff
@@ -386,8 +404,8 @@ func run(args []string) error {
 	// connection mode options
 	fs.BoolVar(&f.zeroIo, "z", false, "zero-I/O mode, report connection status only")
 
-	fs.StringVar(&f.sourcePort, "source-port", netcat.DEFAULT_SOURCE_PORT, "Specify source port to use")
-	fs.StringVar(&f.sourcePort, "p", netcat.DEFAULT_SOURCE_PORT, "Specify source port to use (shorthand)")
+	fs.StringVar(&f.sourcePort, "source-port", "", "Specify source port to use")
```
Comment (rminnich) [inline cmds/core/netcat/netcat.go:407]: why not have this default to netcat.DEFAULT_SOURCE_PORT? Then you would not need that if on line 90 above?
Do we really need all these (shorthand) in the flags? It's kind of obvious it is the shorthand, as it is one letter?

File: cmds/core/netcat/netcat.go [hunk 5]
```diff
@@ -87,8 +87,12 @@ func evalParams(args []string, f flags) (*netcat.Config, error) {
 	// The port is optional as the second argument.
 	switch config.ConnectionMode {
 	case netcat.CONNECTION_MODE_CONNECT:
+		if f.sourcePort == "" {
+			f.sourcePort = netcat.DEFAULT_SOURCE_PORT
+		}
+
 		if len(args) < 1 {
-			return nil, fmt.Errorf("missing host")
+			return nil, fmt.Errorf("%w: missing host", os.ErrInvalid)
```
Comment (rminnich) [inline cmds/core/netcat/netcat.go:95]: I have gotten asked, in reviews, to put the %w last, as it is a convention. Looking at most Go source, I see that is true. I am wondering why you put it first in all these errors?

File: cmds/core/netcat/netcat.go [hunk 6]
```diff
@@ -87,8 +87,12 @@ func evalParams(args []string, f flags) (*netcat.Config, error) {
 	// The port is optional as the second argument.
 	switch config.ConnectionMode {
 	case netcat.CONNECTION_MODE_CONNECT:
+		if f.sourcePort == "" {
```
Comment (rminnich) [inline cmds/core/netcat/netcat.go:90]: You are in a sense recreating the default value you took out in the declaration below, I am wondering why.

File: cmds/core/netcat/netcat.go (hunk 4 above)
Comment (RiSKeD) [reply cmds/core/netcat/netcat.go:407]: The motivation was because of this check:
```
			if f.sourcePort != "" {
				return nil, fmt.Errorf("%w: got more than one port specification", os.ErrInvalid)
			}
```
If in listen mode both host and port are given as arguments, we would not like to receive an additional source port argument via the flag. But if we let the value have a default, this flag is always set to something not equal to "" and we cannot recognize if any value is passed.

Comment (RiSKeD) [reply cmds/core/netcat/netcat.go:407]: If we switch to a default we can only recognize if something else than the default was passed.

File: cmds/core/netcat/netcat.go (hunk 5 above)
Comment (RiSKeD) [reply cmds/core/netcat/netcat.go:95]: I can change the error output to be conventional. But I have to say that `invalid argument: missing host` instead of `missing host: invalid argument` seems more readable.

**Review by rminnich — APPROVED** [review]
