### PR TITLE
Fix bug in insmod, implement lsmod and rmmod

### LINKED ISSUE #245: add insmod, lsmod, rmmod
See summary. A cursory look at init-tools source indicates that it may be enough to just wrap `SYS_INIT_MODULE` and `SYS_DELETE_MODULE`. `lsmod` should only need to look at `/proc/modules`.

### PR DESCRIPTION
**Pull request by rck**
While I intended to work on lsmod/rmmod, I stumbled about a bug in insmod. Boring implementation work ;-), for details please see the according commits.

This was tested with "bb", my current Debian testing kernel (4.13.0-1-amd64), and a simple hello.ko

In sum this Fixes #245.

Regards, rck

### CODE REVIEW

File: cmds/rmmod/rmmod.go [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+)
+
+func main() {
+	if len(os.Args) < 2 {
+		log.Fatalf("rmmod: ERROR: missing module name.\n")
+	}
+
+	modname := os.Args[1]
+	flags := syscall.O_NONBLOCK
+	ret, _, err := syscall.Syscall(syscall.SYS_DELETE_MODULE, uintptr(unsafe.Pointer(&[]byte(modname)[0])), uintptr(len(modname)), uintptr(unsafe.Pointer(&flags)))
```
Comment (hugelgupf) [inline cmds/rmmod/rmmod.go]: https://golang.org/pkg/syscall/#BytePtrFromString

Can be used for the go string to c string conversion

File: cmds/rmmod/rmmod.go [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+	if ret != 0 {
```
Comment (hugelgupf) [inline cmds/rmmod/rmmod.go]: Check err != Nil instead

File: cmds/rmmod/rmmod.go (hunk 1 above)
Comment (hugelgupf) [reply cmds/rmmod/rmmod.go]: The man page I was just looking at just takes a string and flags - why is this also taking the length of the module name and passing a pointer to flags?

Comment (rck) [reply cmds/rmmod/rmmod.go]: The string to byte pointer was taken from the existing insmod, but we could/should switch that, I agree.

For the parameters you are right, it should be something like:
```
syscall.Syscall(syscall.SYS_DELETE_MODULE, uintptr(unsafe.Pointer(&[]byte(modname)[0])),  uintptr(unsafe.Pointer(&flags)), 0)
```

But I think the flags have to be passed as pointer, otherwise they do not match the the type signature.

File: cmds/rmmod/rmmod.go (hunk 2 above)
Comment (rck) [reply cmds/rmmod/rmmod.go]: Hm, if you like. Again, taken from the existing "insmod", and I saw that kind of ret-checking for syscall in the wild. Maybe this would then be an extra patch.

**Comment by rck** [comment]
I will fix the rmmod and send an update when done. Thanks so far.

File: cmds/rmmod/rmmod.go [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+		log.Fatalf("rmmod: ERROR: missing module name.\n")
+	}
+
+	modname := os.Args[1]
+	flags := syscall.O_NONBLOCK
+	modnameptr, err := syscall.BytePtrFromString(modname)
+	if err != nil {
+		log.Fatalf("rmmod: %v\n", err)
+	}
+	ret, _, err := syscall.Syscall(syscall.SYS_DELETE_MODULE, uintptr(unsafe.Pointer(modnameptr)), uintptr(unsafe.Pointer(&flags)), 0)
```
Comment (hugelgupf) [inline cmds/rmmod/rmmod.go]: Instead of passing the flags as a pointer, you can just cast them to uintptr. In fact, constants in go don't have a type. So you don't even need to cast, you can just

```go
syscall.Syscall(..., syscall.O_NONBLOCK, 0)
```

**Comment by hugelgupf** [comment]
The flags need to be passed by value; that's the only way the kernel will accept them, just like with a C implementation of this.

**Comment by hugelgupf** [comment]
And, sorry for the nits - copying from insmod was totally fine, I should go through our existing code and fix what I see to be wrong, though. :) Thank you for the contribution!

File: cmds/rmmod/rmmod.go (hunk 3 above)
Comment (rck) [reply cmds/rmmod/rmmod.go]: Yes, I will keep the "flags" variable, but then it will be uinitprtr(flags). Will push that soon.

File: cmds/insmod/insmod.go [hunk 4]
```diff
@@ -31,7 +29,10 @@ func main() {
 	filename := os.Args[1]
 
 	// Everything else is module options
-	options = strings.Join(os.Args[2:], " ")
+	options := " "
```
[the remark this answers is not in the document]
Comment (rck) [reply cmds/insmod/insmod.go]: @rminnich: Actually this code is outdated, please check the new one, but the new version also contains this check.

This is very weird... the '2' is the start index, and actually this should be index out of bounds. For example change the '2' iin your google-play code to '23' and it fails. IMO '2' is also out of bounds in a two element slice, valid are only '0' and '1'. Very strange. Is this some documented behavior I've never heard of? Or are we just lucky in this case?

File: cmds/rmmod/rmmod.go [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+package main
+
+import (
+	"log"
+	"os"
+	"syscall"
+	"unsafe"
+)
+
+func main() {
```
[the remark this answers is not in the document]
Comment (rck) [reply cmds/rmmod/rmmod.go]: rmmod(8) does, so I fix that and force push again.

File: cmds/insmod/insmod.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (rck) [reply cmds/insmod/insmod.go]: First I thought we are lucky because cap() is longer, which it was not. I could imagine (did not check), that the implementation does a if start == end {return //nothing to do}. And in our case end is len(). Just guessing, but that would at least explain why it does not fail.

**Comment by rck** [comment]
Updated with the version of rmmod that takes multiple modules as arguments.

I kept the check in insmod for "len(os.Args) > 2", but feel free to remove that part for example in an extra commit if you think this is a behavior you want to rely on.

File: cmds/insmod/insmod.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (rminnich) [reply cmds/insmod/insmod.go]: it's the documented behavior. It's  the so-called 'half-open' range. In a two element array, x[2:] is valid and an empty slice.

**Comment by rminnich** [comment]
I'd rather that check come out of the code if  you can. It's not needed.

**Comment by rck** [comment]
@rminnich Good then, pushed.

File: cmds/insmod/insmod.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (rck) [reply cmds/insmod/insmod.go]: @rminnich : I already pushed the version without the check, but out of curiosity, where would that be documented? Yes, I know what an half-open range is, but I can't find any reference that start == len() would be guaranteed to be okay. Any references?

[the remark this answers is not in the document]
Comment (rck) [reply cmds/insmod/insmod.go]: Okay, here we go:
"For arrays or strings, the indices are in range if 0 <= low <= high <= len(a), otherwise they are out of range. For slices, the upper index bound is the slice capacity cap(a) rather than the length." Indeed all "<=". Thanks, learned something new :-)

**Comment by rminnich** [comment]
Thank YOU for tracking this down :-)

File: cmds/insmod/insmod.go [hunk 6]
```diff
@@ -31,15 +29,19 @@ func main() {
 	filename := os.Args[1]
 
 	// Everything else is module options
-	options = strings.Join(os.Args[2:], " ")
+	options := strings.Join(os.Args[2:], " ")
+	optionsptr, err := syscall.BytePtrFromString(options)
```
Comment (rminnich) [inline cmds/insmod/insmod.go]: now that's a new one on me ... good to know.
